version: '3.8'
services:
  product:
    build:
      context: ./product
    ports:
      - "8001:8001"
    networks:
      - ecommerce-network

  order:
    build:
      context: ./order
    ports:
      - "8002:8002"
    networks:
      - ecommerce-network

  user:
    build:
      context: ./user
    ports:
      - "8003:8003"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
